services:
  lib_back_service:
    container_name: 'lib_back'
    image: 'lib_image'
    build: 
      context: . 
    ports:
      - "8001:8000"
    networks:
      - my_network
    env_file:
      - .env

  lib_db_service:
    container_name: 'lib_db'
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "9432:5432"
    volumes:
      - pg-lib-data:/var/lib/postgresql/data
    networks:
      - my_network


volumes:
  pg-lib-data:


networks:
  my_network:
    external: true